CREATE TABLE [dbo].[Nop_Order] (
    [OrderID]                                             INT              IDENTITY (1, 1) NOT NULL,
    [OrderGUID]                                           UNIQUEIDENTIFIER NOT NULL,
    [CustomerID]                                          INT              NOT NULL,
    [CustomerLanguageID]                                  INT              NOT NULL,
    [CustomerTaxDisplayTypeID]                            INT              NOT NULL,
    [CustomerIP]                                          NVARCHAR (50)    NOT NULL,
    [OrderSubtotalInclTax]                                MONEY            NOT NULL,
    [OrderSubtotalExclTax]                                MONEY            NOT NULL,
    [OrderSubTotalDiscountInclTax]                        MONEY            NOT NULL,
    [OrderSubTotalDiscountExclTax]                        MONEY            NOT NULL,
    [OrderShippingInclTax]                                MONEY            NOT NULL,
    [OrderShippingExclTax]                                MONEY            NOT NULL,
    [PaymentMethodAdditionalFeeInclTax]                   MONEY            NOT NULL,
    [PaymentMethodAdditionalFeeExclTax]                   MONEY            NOT NULL,
    [TaxRates]                                            NVARCHAR (4000)  NOT NULL,
    [OrderTax]                                            MONEY            NOT NULL,
    [OrderTotal]                                          MONEY            NOT NULL,
    [RefundedAmount]                                      MONEY            NOT NULL,
    [OrderDiscount]                                       MONEY            NOT NULL,
    [OrderSubtotalInclTaxInCustomerCurrency]              MONEY            NOT NULL,
    [OrderSubtotalExclTaxInCustomerCurrency]              MONEY            NOT NULL,
    [OrderSubTotalDiscountInclTaxInCustomerCurrency]      MONEY            NOT NULL,
    [OrderSubTotalDiscountExclTaxInCustomerCurrency]      MONEY            NOT NULL,
    [OrderShippingInclTaxInCustomerCurrency]              MONEY            NOT NULL,
    [OrderShippingExclTaxInCustomerCurrency]              MONEY            NOT NULL,
    [PaymentMethodAdditionalFeeInclTaxInCustomerCurrency] MONEY            NOT NULL,
    [PaymentMethodAdditionalFeeExclTaxInCustomerCurrency] MONEY            NOT NULL,
    [TaxRatesInCustomerCurrency]                          NVARCHAR (4000)  NOT NULL,
    [OrderTaxInCustomerCurrency]                          MONEY            NOT NULL,
    [OrderTotalInCustomerCurrency]                        MONEY            NOT NULL,
    [OrderDiscountInCustomerCurrency]                     MONEY            NOT NULL,
    [CustomerCurrencyCode]                                NVARCHAR (5)     NOT NULL,
    [CheckoutAttributeDescription]                        NVARCHAR (4000)  NOT NULL,
    [CheckoutAttributesXML]                               XML              NOT NULL,
    [OrderWeight]                                         DECIMAL (18, 4)  NOT NULL,
    [AffiliateID]                                         INT              NOT NULL,
    [OrderStatusID]                                       INT              NOT NULL,
    [AllowStoringCreditCardNumber]                        BIT              NOT NULL,
    [CardType]                                            NVARCHAR (100)   NOT NULL,
    [CardName]                                            NVARCHAR (1000)  NOT NULL,
    [CardNumber]                                          NVARCHAR (100)   NOT NULL,
    [MaskedCreditCardNumber]                              NVARCHAR (100)   NOT NULL,
    [CardCVV2]                                            NVARCHAR (100)   NOT NULL,
    [CardExpirationMonth]                                 NVARCHAR (100)   NOT NULL,
    [CardExpirationYear]                                  NVARCHAR (100)   NOT NULL,
    [PaymentMethodID]                                     INT              NOT NULL,
    [PaymentMethodName]                                   NVARCHAR (100)   NOT NULL,
    [AuthorizationTransactionID]                          NVARCHAR (4000)  NOT NULL,
    [AuthorizationTransactionCode]                        NVARCHAR (4000)  NOT NULL,
    [AuthorizationTransactionResult]                      NVARCHAR (4000)  NOT NULL,
    [CaptureTransactionID]                                NVARCHAR (4000)  NOT NULL,
    [CaptureTransactionResult]                            NVARCHAR (4000)  NOT NULL,
    [SubscriptionTransactionID]                           NVARCHAR (4000)  NOT NULL,
    [PurchaseOrderNumber]                                 NVARCHAR (100)   NOT NULL,
    [PaymentStatusID]                                     INT              NOT NULL,
    [PaidDate]                                            DATETIME         NULL,
    [BillingFirstName]                                    NVARCHAR (100)   NOT NULL,
    [BillingLastName]                                     NVARCHAR (100)   NOT NULL,
    [BillingPhoneNumber]                                  NVARCHAR (50)    NOT NULL,
    [BillingEmail]                                        NVARCHAR (255)   NOT NULL,
    [BillingFaxNumber]                                    NVARCHAR (50)    NOT NULL,
    [BillingCompany]                                      NVARCHAR (100)   NOT NULL,
    [BillingAddress1]                                     NVARCHAR (100)   NOT NULL,
    [BillingAddress2]                                     NVARCHAR (100)   NOT NULL,
    [BillingCity]                                         NVARCHAR (100)   NOT NULL,
    [BillingStateProvince]                                NVARCHAR (100)   NOT NULL,
    [BillingStateProvinceID]                              INT              NOT NULL,
    [BillingZipPostalCode]                                NVARCHAR (30)    NOT NULL,
    [BillingCountry]                                      NVARCHAR (100)   NOT NULL,
    [BillingCountryID]                                    INT              NOT NULL,
    [ShippingStatusID]                                    INT              NOT NULL,
    [ShippingFirstName]                                   NVARCHAR (100)   NOT NULL,
    [ShippingLastName]                                    NVARCHAR (100)   NOT NULL,
    [ShippingPhoneNumber]                                 NVARCHAR (50)    NOT NULL,
    [ShippingEmail]                                       NVARCHAR (255)   NOT NULL,
    [ShippingFaxNumber]                                   NVARCHAR (50)    NOT NULL,
    [ShippingCompany]                                     NVARCHAR (100)   NOT NULL,
    [ShippingAddress1]                                    NVARCHAR (100)   NOT NULL,
    [ShippingAddress2]                                    NVARCHAR (100)   NOT NULL,
    [ShippingCity]                                        NVARCHAR (100)   NOT NULL,
    [ShippingStateProvince]                               NVARCHAR (100)   NOT NULL,
    [ShippingStateProvinceID]                             INT              NOT NULL,
    [ShippingZipPostalCode]                               NVARCHAR (30)    NOT NULL,
    [ShippingCountry]                                     NVARCHAR (100)   NOT NULL,
    [ShippingCountryID]                                   INT              NOT NULL,
    [ShippingMethod]                                      NVARCHAR (100)   NOT NULL,
    [ShippingRateComputationMethodID]                     INT              NOT NULL,
    [ShippedDate]                                         DATETIME         NULL,
    [TrackingNumber]                                      NVARCHAR (100)   NOT NULL,
    [DeliveryDate]                                        DATETIME         NULL,
    [VatNumber]                                           NVARCHAR (100)   NOT NULL,
    [Deleted]                                             BIT              NOT NULL,
    [CreatedOn]                                           DATETIME         NOT NULL
);

