ALTER TABLE [dbo].[Nop_RecurringPaymentHistory]
    ADD CONSTRAINT [Nop_RecurringPaymentHistory_PK] PRIMARY KEY CLUSTERED ([RecurringPaymentHistoryID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

