ALTER TABLE [dbo].[Nop_Discount]
    ADD CONSTRAINT [Nop_Discount_PK] PRIMARY KEY CLUSTERED ([DiscountID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

