ALTER TABLE [dbo].[Nop_SearchLog]
    ADD CONSTRAINT [PK_Nop_SearchLog] PRIMARY KEY CLUSTERED ([SearchLogID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

