ALTER TABLE [dbo].[Nop_ReturnRequest]
    ADD CONSTRAINT [PK_Nop_ReturnRequest] PRIMARY KEY CLUSTERED ([ReturnRequestId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

