ALTER TABLE [dbo].[Nop_ProductAttributeLocalized]
    ADD CONSTRAINT [PK_Nop_ProductAttributeLocalized] PRIMARY KEY CLUSTERED ([ProductAttributeLocalizedID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

