ALTER TABLE [dbo].[Nop_SMSProvider]
    ADD CONSTRAINT [PK_SMSProvider] PRIMARY KEY CLUSTERED ([SMSProviderId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

