ALTER TABLE [dbo].[Nop_ShippingRateComputationMethod]
    ADD CONSTRAINT [PK_ShippingRateComputationMethod] PRIMARY KEY CLUSTERED ([ShippingRateComputationMethodID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

