ALTER TABLE [dbo].[Nop_Address]
    ADD CONSTRAINT [Nop_Address_PK] PRIMARY KEY CLUSTERED ([AddressId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

