ALTER TABLE [dbo].[Nop_ProductTemplate]
    ADD CONSTRAINT [Nop_ProductTemplate_PK] PRIMARY KEY CLUSTERED ([ProductTemplateId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

