ALTER TABLE [dbo].[Nop_ProductVariant]
    ADD CONSTRAINT [Nop_ProductVariant_PK] PRIMARY KEY CLUSTERED ([ProductVariantId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

