//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NopSolutions.NopCommerce.Web.VendorAdministration.Modules {
    
    
    public partial class ForumsSettingsControl {
        
        /// <summary>
        /// btnSave control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSave;
        
        /// <summary>
        /// lblForumsEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblForumsEnabled;
        
        /// <summary>
        /// cbForumsEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbForumsEnabled;
        
        /// <summary>
        /// lblRelativeDateTimeFormattingEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblRelativeDateTimeFormattingEnabled;
        
        /// <summary>
        /// cbRelativeDateTimeFormattingEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbRelativeDateTimeFormattingEnabled;
        
        /// <summary>
        /// lblShowCustomersPostCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblShowCustomersPostCount;
        
        /// <summary>
        /// cbShowCustomersPostCount control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbShowCustomersPostCount;
        
        /// <summary>
        /// lblGuestsAllowedToCreatePosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblGuestsAllowedToCreatePosts;
        
        /// <summary>
        /// cbGuestsAllowedToCreatePosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbGuestsAllowedToCreatePosts;
        
        /// <summary>
        /// lblGuestsAllowedToCreateTopics control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblGuestsAllowedToCreateTopics;
        
        /// <summary>
        /// cbGuestsAllowedToCreateTopics control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbGuestsAllowedToCreateTopics;
        
        /// <summary>
        /// lblCustomersAllowedToEditPosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblCustomersAllowedToEditPosts;
        
        /// <summary>
        /// cbCustomersAllowedToEditPosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbCustomersAllowedToEditPosts;
        
        /// <summary>
        /// lblCustomersAllowedToDeletePosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblCustomersAllowedToDeletePosts;
        
        /// <summary>
        /// cbCustomersAllowedToDeletePosts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbCustomersAllowedToDeletePosts;
        
        /// <summary>
        /// lblCustomersAllowedToManageSubscriptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblCustomersAllowedToManageSubscriptions;
        
        /// <summary>
        /// cbCustomersAllowedToManageSubscriptions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbCustomersAllowedToManageSubscriptions;
        
        /// <summary>
        /// lblTopicsPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblTopicsPageSize;
        
        /// <summary>
        /// txtTopicsPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.NumericTextBox txtTopicsPageSize;
        
        /// <summary>
        /// lblPostsPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblPostsPageSize;
        
        /// <summary>
        /// txtPostsPageSize control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.NumericTextBox txtPostsPageSize;
        
        /// <summary>
        /// lblForumEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblForumEditor;
        
        /// <summary>
        /// ddlForumEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlForumEditor;
        
        /// <summary>
        /// lblSignatureEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblSignatureEnabled;
        
        /// <summary>
        /// cbSignatureEnabled control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox cbSignatureEnabled;
    }
}
