//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NopSolutions.NopCommerce.Web.VendorAdministration.Modules {
    
    
    public partial class SpecificationAttributeInfoControl {
        
        /// <summary>
        /// rptrLanguageTabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptrLanguageTabs;
        
        /// <summary>
        /// lblName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblName;
        
        /// <summary>
        /// txtName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.SimpleTextBox txtName;
        
        /// <summary>
        /// rptrLanguageDivs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptrLanguageDivs;
        
        /// <summary>
        /// lblDisplayOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.ToolTipLabelControl lblDisplayOrder;
        
        /// <summary>
        /// txtDisplayOrder control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NopSolutions.NopCommerce.Web.VendorAdministration.Modules.NumericTextBox txtDisplayOrder;
    }
}
