ALTER TABLE [dbo].[Nop_CrossSellProduct]
    ADD CONSTRAINT [IX_Nop_CrossSellProduct_Unique] UNIQUE NONCLUSTERED ([ProductId1] ASC, [ProductId2] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

