ALTER TABLE [dbo].[Nop_OrderProductVariant]
    ADD CONSTRAINT [Nop_OrderProductVariant_PK] PRIMARY KEY CLUSTERED ([OrderProductVariantID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

