ALTER TABLE [dbo].[Nop_Product]
    ADD CONSTRAINT [Nop_Product_PK] PRIMARY KEY CLUSTERED ([ProductId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

