ALTER TABLE [dbo].[Nop_RelatedProduct]
    ADD CONSTRAINT [IX_Nop_RelatedProduct_Unique] UNIQUE NONCLUSTERED ([ProductID1] ASC, [ProductID2] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

