ALTER TABLE [dbo].[Nop_GiftCard]
    ADD CONSTRAINT [Nop_GiftCard_PK] PRIMARY KEY CLUSTERED ([GiftCardID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

