ALTER TABLE [dbo].[Nop_ACL]
    ADD CONSTRAINT [Nop_ACL_PK] PRIMARY KEY CLUSTERED ([ACLID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

