ALTER TABLE [dbo].[Nop_CrossSellProduct]
    ADD CONSTRAINT [PK_CrossSellProduct] PRIMARY KEY CLUSTERED ([CrossSellProductId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

