ALTER TABLE [dbo].[Nop_ActivityLogType]
    ADD CONSTRAINT [PK_Nop_ActivityLogType] PRIMARY KEY CLUSTERED ([ActivityLogTypeID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

