ALTER TABLE [dbo].[Nop_ProductRating]
    ADD CONSTRAINT [PK_Nop_ProductRating] PRIMARY KEY CLUSTERED ([ProductRatingID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

