ALTER TABLE [dbo].[Nop_Pricelist]
    ADD CONSTRAINT [PK_Nop_Pricelist] PRIMARY KEY CLUSTERED ([PricelistID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

