ALTER TABLE [dbo].[Nop_Setting]
    ADD CONSTRAINT [IX_Nop_Setting] UNIQUE NONCLUSTERED ([Name] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF) ON [PRIMARY];

