ALTER TABLE [dbo].[Nop_ShoppingCartItem]
    ADD CONSTRAINT [Nop_ShoppingCart_PK] PRIMARY KEY CLUSTERED ([ShoppingCartItemID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

