ALTER TABLE [dbo].[Nop_DiscountRestriction]
    ADD CONSTRAINT [Nop_DiscountRestriction_PK] PRIMARY KEY CLUSTERED ([ProductVariantID] ASC, [DiscountID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

