ALTER TABLE [dbo].[Nop_ACLPerObject]
    ADD CONSTRAINT [PK_ACLPerObject] PRIMARY KEY CLUSTERED ([ACLPerObjectId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

