ALTER TABLE [dbo].[Nop_EmailAccount]
    ADD CONSTRAINT [PK_EmailAccount] PRIMARY KEY CLUSTERED ([EmailAccountId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

