ALTER TABLE [dbo].[Nop_Topic]
    ADD CONSTRAINT [PK_Nop_Topic] PRIMARY KEY CLUSTERED ([TopicID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

