ALTER TABLE [dbo].[Nop_CategoryLocalized]
    ADD CONSTRAINT [PK_Nop_CategoryLocalized] PRIMARY KEY CLUSTERED ([CategoryLocalizedID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

