ALTER TABLE [dbo].[Nop_ProductLocalized]
    ADD CONSTRAINT [PK_Nop_ProductLocalized] PRIMARY KEY CLUSTERED ([ProductLocalizedID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

