ALTER TABLE [dbo].[Nop_SpecificationAttribute]
    ADD CONSTRAINT [PK_Nop_SpecificationAttribute] PRIMARY KEY CLUSTERED ([SpecificationAttributeID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

