ALTER TABLE [dbo].[Nop_QBEntity]
    ADD CONSTRAINT [PK_Nop_QBEntity] PRIMARY KEY CLUSTERED ([EntityId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

