ALTER TABLE [dbo].[Nop_DiscountUsageHistory]
    ADD CONSTRAINT [Nop_DiscountUsageHistory_PK] PRIMARY KEY CLUSTERED ([DiscountUsageHistoryID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

