ALTER TABLE [dbo].[Nop_CategoryTemplate]
    ADD CONSTRAINT [Nop_CategoryTemplate_PK] PRIMARY KEY CLUSTERED ([CategoryTemplateId] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

