ALTER TABLE [dbo].[Nop_Order]
    ADD CONSTRAINT [PK__Nop_Order__035179CE] PRIMARY KEY CLUSTERED ([OrderID] ASC) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

